/*
   -- Main_arm --
   
   To compile this code using RemoteXY library 4.1.4 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.16.02 or later version;
     - for iOS 1.13.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__ESP32CORE_BLE

#include <BLEDevice.h>

// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "MainArm"


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t RemoteXY_CONF[] = // 143 bytes
{ 255,8,0,0,0,136,0,19,0,0,0,0,31,2,106,200,200,84,1,1,
8,0,4,29,14,7,86,89,252,12,90,48,2,26,4,10,218,7,86,122,
252,12,92,48,2,26,4,68,12,7,86,153,251,11,92,48,2,26,1,241,
12,57,57,17,12,17,17,0,2,31,226,135,166,0,1,255,0,57,57,42,
12,16,16,0,2,31,226,135,168,0,1,240,98,57,57,17,51,16,16,0,
2,31,226,135,166,0,1,16,105,38,38,42,51,16,16,0,2,31,226,135,
168,0,2,11,69,23,52,26,33,26,9,0,2,26,31,31,79,78,0,79,
70,70,0 };

// this structure defines all the variables and events of your control interface
struct {

// input variables
int8_t slider_01; // from -100 to 100
int8_t slider_02; // from -100 to 100
int8_t slider_03; // from -100 to 100
uint8_t button_01; // =1 if button pressed, else =0, from 0 to 1
uint8_t button_02; // =1 if button pressed, else =0, from 0 to 1
uint8_t button_03; // =1 if button pressed, else =0, from 0 to 1
uint8_t button_04; // =1 if button pressed, else =0, from 0 to 1
uint8_t switch_01; // =1 if switch ON and =0 if OFF, from 0 to 1
// other variable
uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

#include <ESP32Servo.h>

Servo servoL;
Servo servoR;
int angleR=30;
int angleL=60;

int pinX1=13;
int pinX2=12;
int pinY1=14;
int pinY2=27;
int pinZ1=26;
int pinZ2=25;

int handL=2;
int handR=15;

//int led=2

void setup() {
  RemoteXY_Init();
  servoL.setPeriodHertz(50);
  servoR.setPeriodHertz(50);
  servoL.attach(handL);
  servoR.attach(handR);
  ledcAttach(pinX1,12800,8);
  ledcAttach(pinX2,12800,8);
  ledcAttach(pinY1,12800,8);
  ledcAttach(pinY2,12800,8);
  ledcAttach(pinZ1,12800,8);
  ledcAttach(pinZ2,12800,8);
  //pinMode(led,OUTPUT);
}

void loop() {
  RemoteXY_Handler();
  if(RemoteXY.connect_flag==1){
    move(RemoteXY.slider_01,pinX1,pinX2);
    move(RemoteXY.slider_02,pinY1,pinY2);
    move(RemoteXY.slider_03,pinZ1,pinZ2);

    servoL.write(angleL);
    servoR.write(angleR);
    RemoteXY_delay(10);

    if(RemoteXY.switch_01==1){
      angleR=(angleR+(180-angleL))/2;
      angleL=180-angleR;
      if(RemoteXY.button_01+RemoteXY.button_03>0 && angleL<180){
        angleL+=2;//1;
        //angleR-=1;
      }
      else if(RemoteXY.button_02+RemoteXY.button_04>0 && angleR>0){
        angleL-=2;//1;
        //angleR+=1;
      }
    }
    else{
      if(RemoteXY.button_02==1 && angleL<180){
        angleL+=1;
      }
      else if(RemoteXY.button_01==1 && angleL>0){
        angleL-=1;
      }

      if(RemoteXY.button_04==1 && angleR<180){
        angleR+=1;
      }
      else if(RemoteXY.button_03==1 && angleR>0){
        angleR-=1;
      }
    }
  }
  else{// buetooth未接続状態の挙動
    //digitalWrite(led,HIGH);
    //RemoteXY_delay(500);
    //digitalWrite(led,LOW);
    //RemoteXY_delay(500);
  }
}

void move(int position, int pin1, int pin2) {
  if(position > 0){
    ledcWrite(pin1,position);
    ledcWrite(pin2,0);
  }
  else if(position < 0){
    ledcWrite(pin1,0);
    ledcWrite(pin2,-position);
  }
  else{
    ledcWrite(pin1,0);
    ledcWrite(pin2,0);
  }
}
