/*
   -- New project --
   
   To compile this code using RemoteXY library 4.1.4 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.16.02 or later version;
     - for iOS 1.13.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG

// RemoteXY select connection mode and include library
#define REMOTEXY_MODE__ESP32CORE_BLE

#include <BLEDevice.h>

// RemoteXY connection settings
#define REMOTEXY_BLUETOOTH_NAME "Aigis_main"


#include <RemoteXY.h>

// RemoteXY GUI configuration
#pragma pack(push, 1)
uint8_t RemoteXY_CONF[] =  // 213 bytes
  { 255, 6, 0, 0, 0, 206, 0, 19, 0, 0, 0, 0, 31, 2, 106, 200, 200, 92, 1, 1,
    11, 0, 4, 40, 87, 7, 78, 9, 66, 130, 19, 160, 2, 26, 10, 242, 122, 52, 52, 23,
    22, 21, 21, 48, 4, 26, 31, 79, 78, 0, 31, 79, 70, 70, 0, 4, 79, 35, 7, 78,
    139, 250, 17, 103, 32, 2, 26, 4, 88, 13, 9, 224, 168, 250, 17, 103, 32, 2, 26, 1,
    26, 48, 52, 52, 72, 22, 21, 21, 0, 2, 31, 233, 160, 134, 0, 129, 252, 20, 63, 26,
    11, 12, 49, 7, 0, 24, 227, 131, 153, 227, 131, 171, 227, 131, 136, 227, 130, 179, 227, 131,
    179, 227, 131, 153, 227, 130, 162, 0, 129, 237, 81, 105, 15, 89, 12, 21, 7, 0, 24, 227,
    131, 143, 227, 131, 179, 227, 131, 137, 0, 1, 42, 46, 52, 52, 106, 21, 21, 21, 0, 2,
    31, 233, 128, 134, 0, 129, 38, 102, 45, 15, 68, 52, 12, 7, 0, 24, 88, 232, 187, 184,
    0, 129, 47, 133, 25, 15, 125, 4, 12, 7, 0, 24, 89, 232, 187, 184, 0, 129, 58, 70,
    25, 15, 186, 4, 12, 7, 0, 24, 90, 232, 187, 184, 0 };

// this structure defines all the variables and events of your control interface
struct {

  // input variables
  int8_t slider_01;       // from -100 to 100
  uint8_t pushSwitch_01;  // =1 if state is ON, else =0, from 0 to 1
  int8_t slider_02;       // from -100 to 100
  int8_t slider_03;       // from -100 to 100
  uint8_t button_01;      // =1 if button pressed, else =0, from 0 to 1
  uint8_t button_02;      // =1 if button pressed, else =0, from 0 to 1

  // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;
#pragma pack(pop)

/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

#include <ESP32Servo.h>
Servo servo;
// Pins
#define DCMotor 2
#define ServoMotor 0
#define Motor1 34 
#define Motor2 35
#define Motor3 25
#define Motor4 26
#define Motor5 27
#define Motor6 14

#define buffer 5

void setup() {
  RemoteXY_Init();

  pinMode(DCMotor, OUTPUT);

  ledcAttach(Motor1, 12800, 8);
  ledcAttach(Motor2, 12800, 8);
  ledcAttach(Motor3, 12800, 8);
  ledcAttach(Motor4, 12800, 8);
  ledcAttach(Motor5, 12800, 8);
  ledcAttach(Motor6, 12800, 8);
  
  servo.setPeriodHeltz(50);
  servo.attach(ServoMotor, 500, 2400);
}

void loop() {
  RemoteXY_Handler();
  if (RemoteXY.connect_flag == 1) {
    Belt(RemoteXY.pushSwitch_01);
    Hand(RemoteXY.button_01, RemoteXY.button_02);
    Xmove(RemoteXY.slider_01);
    Ymove(RemoteXY.slider_02);
    Zmove(RemoteXY.slider_03);
  }
  else{
    analogWrite(DCMotor,HIGH.0)
  }
}

void Belt(int is_on) {
  if(is_on == 1){
    digitalWrite(DCMotor,HIGH);
  }
  else{
    digitalWrite(DCMotor,LOW);
  }
}

void Hand(int forward, int reverse) {
  if(forward == 1 && reverse == 0 && )
}

void Xmove(int Xposition) {
  if(Xposition > buffer){
    ledcWrite(Motor1,Xposition);
    ledcWrite(Motor2,0);
  }
  else if(Xposition < -buffer){
    ledcWrite(Motor1,0);
    ledcWrite(Motor2,Xposition);
  }
  else{
    ledcWrite(Motor1,0);
    ledcWrite(Motor2,0);
  }
}

void Ymove(int Yposition) {
  ...
}

void Zmove(int Zposition) {
  ...
}