/*
   -- Aigis_ver2 --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual:
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__ESP32CORE_BLUETOOTH

#include <BluetoothSerial.h>

// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "Aigis_ver2"


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 80 bytes V19 
  { 255,5,0,0,0,73,0,19,0,0,0,0,28,2,106,200,200,84,1,1,
  4,0,5,238,21,143,143,69,8,69,69,32,2,26,31,4,17,26,7,86,
  157,2,14,83,48,2,26,4,38,67,7,86,11,56,56,13,176,2,26,10,
  248,22,57,57,31,17,18,18,49,134,26,31,79,78,0,31,79,70,70,0 };  

// this structure defines all the variables and events of your control interface 
struct {
    // input variables
  int8_t joystick_01_x; // from -100 to 100
  int8_t joystick_01_y; // from -100 to 100
  int8_t slider_01; // from -100 to 100
  int8_t slider_02; // from -100 to 100
  uint8_t pushSwitch_01; // =1 if state is ON, else =0, from 0 to 1
    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////


#include <AnalogMotorDriver.h>
#include <ESP32Servo.h>

const uint8_t pin_xmotor[] = {14,27};
const uint8_t pin_ymotor[] = {26,25};
const uint8_t pin_zmotor[] = {33,32};
const uint8_t pin_rhand = 18;
const uint8_t pin_lhand = 19;
const uint8_t pin_led = 2;


const int range_ignore = 10;

const int hand_max = 60;
const int hand_min = 0;
const int hand_speed = 2;


AnalogMotor Xmotor;
AnalogMotor Ymotor;
AnalogMotor Zmotor;

int hand_angle;
Servo Rhand, Lhand;


void setup(){
  RemoteXY_Init();

  Rhand.attach(pin_rhand);
  Lhand.attach(pin_lhand);

  ledcAttach(pin_led, 12800, 8);

  Xmotor.attach(pin_xmotor);
  Ymotor.attach(pin_ymotor);
  Zmotor.attach(pin_zmotor);
}

void loop(){
  RemoteXYEngine.handler();
  if(RemoteXY.connect_flag && RemoteXY.pushSwitch_01){
    
    Xmotor.move(RemoteXY.joystick_01_x>range_ignore? RemoteXY.joystick_01_x*2: 0);
    Ymotor.move(RemoteXY.joystick_01_y>range_ignore? RemoteXY.joystick_01_y*2: 0);
    Zmotor.move(RemoteXY.slider_01>range_ignore? RemoteXY.slider_01*2: 0);
    
    hand_angle = constrain((abs(RemoteXY.slider_02) > range_ignore? sign(RemoteXY.slider_02)*hand_speed: 0) + hand_angle, hand_min, hand_max);
    Rhand.write(180-hand_angle);
    Lhand.write(hand_angle);

    ledcWrite(pin_led, 200);
  }
  else{
    Xmotor.move(0);
    Ymotor.move(0);
    Zmotor.move(0);
    /*
    Lhand.write(90);
    Rhand.write(180);
    RemoteXYEngine.delay(1000);
    Lhand.write(0);
    Rhand.write(90);
    RemoteXYEngine.delay(1000);
    //*/
    ledcWrite(pin_led, 0);
  }

}

int sign(int x){
  return (x>0)-(x<0);
}