
/*
   -- Aigis_ver2 --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual:
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__ESP32CORE_BLUETOOTH

#include <BluetoothSerial.h>

// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "Aigis_ver2"


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 80 bytes V19 
  { 255,5,0,0,0,73,0,19,0,0,0,0,28,2,106,200,200,84,1,1,
  4,0,5,238,21,143,143,69,8,69,69,32,2,26,31,4,17,26,7,86,
  157,2,14,83,48,2,26,4,38,67,7,86,11,56,56,13,176,2,26,10,
  248,22,57,57,31,17,18,18,49,134,26,31,79,78,0,31,79,70,70,0 };
  
// this structure defines all the variables and events of your control interface 
struct {
    // input variables
  int8_t joystick_01_x; // from -100 to 100
  int8_t joystick_01_y; // from -100 to 100
  int8_t slider_01; // from -100 to 100
  int8_t slider_02; // from -100 to 100
  uint8_t pushSwitch_01; // =1 if state is ON, else =0, from 0 to 1
    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

#include <ESP32Servo.h>

enum MOTOR_ID{
  X_AXIS, Y_AXIS, Z_AXIS, HAND, LED=8
};

const int ignore_range[] = {
  15, 15, 15, 5
};

const int pins[] = {
//x1  x2  y1  y2  z1  z2   hand  led
  2, 12, 14, 27, 26, 25, 15, 33, 13
};

int hand_angle;
const int hand_max = 60, hand_min = 0;
const int hand_speed = 2;
Servo hand_R;
Servo hand_L;

void setup(){
  RemoteXY_Init();
  for(int i=0; i<6; i++){
    ledcAttach(pins[i], 12800, 8);
    //ledcWrite(pins[i], 0);
  }
  //ledcAttach(pins[0],12800,8);
  //hand_R.setPeriodHertz(50);
  //hand_L.setPeriodHertz(50);
  hand_R.attach(pins[6]);//500,2400);
  hand_L.attach(pins[7]);
  ledcAttach(pins[LED], 12800, 8);
  //ledcAttach(pins[5], 12800, 8);
  Serial.begin(9600);
}

void loop(){
  RemoteXYEngine.handler();
  if(RemoteXY.connect_flag && RemoteXY.pushSwitch_01){
    ledcWrite(pins[LED], 0);

    //x軸移動
    //driveMotor(X_AXIS, abs(RemoteXY.joystick_01_x) > ignore_range[X_AXIS]? RemoteXY.joystick_01_x*2: 0);
  
    //y軸移動
    //driveMotor(Y_AXIS, abs(RemoteXY.joystick_01_y) > ignore_range[Y_AXIS]? RemoteXY.joystick_01_y*2: 0);

    //z軸移動
    //driveMotor(Z_AXIS, abs(RemoteXY.slider_01) > ignore_range[Z_AXIS]? RemoteXY.slider_01*2: 0);
  
    //ハンド開閉
    hand_angle = constrain((abs(RemoteXY.slider_02) > ignore_range[HAND]? sign(RemoteXY.slider_02)*hand_speed: 0) + hand_angle, hand_min, hand_max);
    hand_R.write(hand_angle);
    hand_L.write(180-hand_angle);
    Serial.println(hand_angle);
    //RemoteXYEngine.delay(10);

  }else{
    //for(int i=0; i<6; i++){
      //ledcWrite(pins[i], 0);
    //}
    ledcWrite(pins[LED], 200);
    hand_R.write(90);
    hand_L.write(90);
    RemoteXYEngine.delay(500);
    hand_R.write(0);
    hand_L.write(0);
    RemoteXYEngine.delay(500);
  }
  // do not call delay(), use instead RemoteXYEngine.delay() 
}

void driveMotor(int idx, int speed){
  ledcWrite(pins[idx*2], speed>0? speed: 0);
  ledcWrite(pins[idx*2+1], speed<0? -speed: 0);
}

int sign(int x){
  return (x>0)-(x<0);
}